name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:         # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gera a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: simonebatista23
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publica no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
